name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Import Badges
        run: |
          echo "${{ secrets.BADGE_GENERIC }}" | base64 --decode > src/MlsaBadgeMaker.Api/Resources/Badges/MSLearn_SA_Profile_Badge_Overlay_GENERIC.png && \
          echo "${{ secrets.BADGE_ALPHA }}" | base64 --decode > src/MlsaBadgeMaker.Api/Resources/Badges/MSLearn_SA_Profile_Badge_Overlay_ALPHA.png && \
          echo "${{ secrets.BADGE_BETA }}" | base64 --decode > src/MlsaBadgeMaker.Api/Resources/Badges/MSLearn_SA_Profile_Badge_Overlay_BETA.png && \
          echo "${{ secrets.BADGE_GOLD }}" | base64 --decode > src/MlsaBadgeMaker.Api/Resources/Badges/MSLearn_SA_Profile_Badge_Overlay_GOLD.png
      - name: Verify Badges
        run: ls -lh src/MlsaBadgeMaker.Api/Resources/Badges
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_FIELD_0FFCC9903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src/MlsaBadgeMaker.App" # App source code path
          api_location: "src/MlsaBadgeMaker.Api" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_FIELD_0FFCC9903 }}
          action: "close"
